name: Build and Deploy Static Web App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # set in repository secrets
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Automatic
          action: 'upload'
          #### Update these to match your app structure ####
          app_location: '/' # App source code path
          api_location: 'api' # Api location, set to empty string if none
          output_location: 'dist' # Built app content directory
